//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnWebServices.WS.Prefill
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    public partial class AltinnFault : object
    {
        
        private string AltinnErrorMessageField;
        
        private string AltinnExtendedErrorMessageField;
        
        private string AltinnLocalizedErrorMessageField;
        
        private string ErrorGuidField;
        
        private int ErrorIDField;
        
        private string UserGuidField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage
        {
            get
            {
                return this.AltinnErrorMessageField;
            }
            set
            {
                this.AltinnErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage
        {
            get
            {
                return this.AltinnExtendedErrorMessageField;
            }
            set
            {
                this.AltinnExtendedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage
        {
            get
            {
                return this.AltinnLocalizedErrorMessageField;
            }
            set
            {
                this.AltinnLocalizedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid
        {
            get
            {
                return this.ErrorGuidField;
            }
            set
            {
                this.ErrorGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillFormTask", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    public partial class PrefillFormTask : object
    {
        
        private string ExternalServiceCodeField;
        
        private int ExternalServiceEditionCodeField;
        
        private string ExternalShipmentReferenceField;
        
        private string IdentityFieldHashCodeField;
        
        private System.Guid LargeInboundReferenceField;
        
        private AltinnWebServices.WS.Prefill.PrefillAttachmentBEList PreFillAttachmentsField;
        
        private AltinnWebServices.WS.Prefill.PrefillFormBEList PreFillFormsField;
        
        private AltinnWebServices.WS.Prefill.PreFillIdentityFieldBEList PreFillIdentityFieldsField;
        
        private AltinnWebServices.WS.Prefill.NotificationBEList PrefillNotificationsField;
        
        private string ReceiversReferenceField;
        
        private string ReporteeField;
        
        private string SendersReferenceField;
        
        private string ServiceOwnerCodeField;
        
        private System.DateTime ValidFromDateField;
        
        private System.DateTime ValidToDateField;
        
        private System.Nullable<bool> IsReservableField;
        
        private bool ValidateButDoNotSendNotificationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalServiceCode
        {
            get
            {
                return this.ExternalServiceCodeField;
            }
            set
            {
                this.ExternalServiceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExternalServiceEditionCode
        {
            get
            {
                return this.ExternalServiceEditionCodeField;
            }
            set
            {
                this.ExternalServiceEditionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalShipmentReference
        {
            get
            {
                return this.ExternalShipmentReferenceField;
            }
            set
            {
                this.ExternalShipmentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityFieldHashCode
        {
            get
            {
                return this.IdentityFieldHashCodeField;
            }
            set
            {
                this.IdentityFieldHashCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LargeInboundReference
        {
            get
            {
                return this.LargeInboundReferenceField;
            }
            set
            {
                this.LargeInboundReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.PrefillAttachmentBEList PreFillAttachments
        {
            get
            {
                return this.PreFillAttachmentsField;
            }
            set
            {
                this.PreFillAttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.PrefillFormBEList PreFillForms
        {
            get
            {
                return this.PreFillFormsField;
            }
            set
            {
                this.PreFillFormsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.PreFillIdentityFieldBEList PreFillIdentityFields
        {
            get
            {
                return this.PreFillIdentityFieldsField;
            }
            set
            {
                this.PreFillIdentityFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.NotificationBEList PrefillNotifications
        {
            get
            {
                return this.PrefillNotificationsField;
            }
            set
            {
                this.PrefillNotificationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiversReference
        {
            get
            {
                return this.ReceiversReferenceField;
            }
            set
            {
                this.ReceiversReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reportee
        {
            get
            {
                return this.ReporteeField;
            }
            set
            {
                this.ReporteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendersReference
        {
            get
            {
                return this.SendersReferenceField;
            }
            set
            {
                this.SendersReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServiceOwnerCode
        {
            get
            {
                return this.ServiceOwnerCodeField;
            }
            set
            {
                this.ServiceOwnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ValidFromDate
        {
            get
            {
                return this.ValidFromDateField;
            }
            set
            {
                this.ValidFromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ValidToDate
        {
            get
            {
                return this.ValidToDateField;
            }
            set
            {
                this.ValidToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<bool> IsReservable
        {
            get
            {
                return this.IsReservableField;
            }
            set
            {
                this.IsReservableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool ValidateButDoNotSendNotification
        {
            get
            {
                return this.ValidateButDoNotSendNotificationField;
            }
            set
            {
                this.ValidateButDoNotSendNotificationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PrefillAttachmentBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PrefillFormTaskAttachment")]
    public class PrefillAttachmentBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.PrefillFormTaskAttachment>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PrefillFormBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PrefillForm")]
    public class PrefillFormBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.PrefillForm>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PreFillIdentityFieldBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PreFillIdentityFieldBE")]
    public class PreFillIdentityFieldBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.PreFillIdentityFieldBE>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="NotificationBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="Notification")]
    public class NotificationBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.Notification>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillFormTaskAttachment", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    public partial class PrefillFormTaskAttachment : object
    {
        
        private byte[] AttachmentDataField;
        
        private string AttachmentNameField;
        
        private AltinnWebServices.WS.Prefill.AttachmentType AttachmentTypeField;
        
        private string FileNameField;
        
        private string SendersReferenceField;
        
        private System.Nullable<bool> SignedByDefaultField;
        
        private System.Nullable<bool> SigningLockedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] AttachmentData
        {
            get
            {
                return this.AttachmentDataField;
            }
            set
            {
                this.AttachmentDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AttachmentName
        {
            get
            {
                return this.AttachmentNameField;
            }
            set
            {
                this.AttachmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AltinnWebServices.WS.Prefill.AttachmentType AttachmentType
        {
            get
            {
                return this.AttachmentTypeField;
            }
            set
            {
                this.AttachmentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SendersReference
        {
            get
            {
                return this.SendersReferenceField;
            }
            set
            {
                this.SendersReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SignedByDefault
        {
            get
            {
                return this.SignedByDefaultField;
            }
            set
            {
                this.SignedByDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SigningLocked
        {
            get
            {
                return this.SigningLockedField;
            }
            set
            {
                this.SigningLockedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentType", Namespace="http://schemas.altinn.no/services/serviceEntity/2009/10")]
    public enum AttachmentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_pdf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_msword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_ms_excel = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_text = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_presentation = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_spreadsheet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_rtf = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_ms_powerpoint = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_postscript = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_zip = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_plain = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_html = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_xml = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_rtf = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_richtext = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        binary_octet_stream = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        not_Applicable = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTOM = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BASE64 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_jpeg = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_gif = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_bmp = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        formtask_pdf = 23,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillForm", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    public partial class PrefillForm : object
    {
        
        private string DataFormatIDField;
        
        private int DataFormatVersionField;
        
        private string FormDataXMLField;
        
        private string SendersReferenceField;
        
        private System.Nullable<bool> SignedByDefaultField;
        
        private System.Nullable<bool> SigningLockedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DataFormatID
        {
            get
            {
                return this.DataFormatIDField;
            }
            set
            {
                this.DataFormatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DataFormatVersion
        {
            get
            {
                return this.DataFormatVersionField;
            }
            set
            {
                this.DataFormatVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FormDataXML
        {
            get
            {
                return this.FormDataXMLField;
            }
            set
            {
                this.FormDataXMLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SendersReference
        {
            get
            {
                return this.SendersReferenceField;
            }
            set
            {
                this.SendersReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SignedByDefault
        {
            get
            {
                return this.SignedByDefaultField;
            }
            set
            {
                this.SignedByDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SigningLocked
        {
            get
            {
                return this.SigningLockedField;
            }
            set
            {
                this.SigningLockedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreFillIdentityFieldBE", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    public partial class PreFillIdentityFieldBE : object
    {
        
        private string FieldValueField;
        
        private string IndexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldValue
        {
            get
            {
                return this.FieldValueField;
            }
            set
            {
                this.FieldValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                this.IndexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    public partial class Notification : object
    {
        
        private string FromAddressField;
        
        private int NotificationIDField;
        
        private AltinnWebServices.WS.Prefill.NotificationType NotifyTypeField;
        
        private int ReporteeElementIDField;
        
        private System.Nullable<int> ReporteeIdField;
        
        private System.DateTime ShipmentDateTimeField;
        
        private string LanguageCodeField;
        
        private string NotificationTypeField;
        
        private AltinnWebServices.WS.Prefill.TextTokenSubstitutionBEList TextTokensField;
        
        private AltinnWebServices.WS.Prefill.ReceiverEndPointBEList ReceiverEndPointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                this.FromAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotificationID
        {
            get
            {
                return this.NotificationIDField;
            }
            set
            {
                this.NotificationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.NotificationType NotifyType
        {
            get
            {
                return this.NotifyTypeField;
            }
            set
            {
                this.NotifyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReporteeElementID
        {
            get
            {
                return this.ReporteeElementIDField;
            }
            set
            {
                this.ReporteeElementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReporteeId
        {
            get
            {
                return this.ReporteeIdField;
            }
            set
            {
                this.ReporteeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShipmentDateTime
        {
            get
            {
                return this.ShipmentDateTimeField;
            }
            set
            {
                this.ShipmentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LanguageCode
        {
            get
            {
                return this.LanguageCodeField;
            }
            set
            {
                this.LanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public AltinnWebServices.WS.Prefill.TextTokenSubstitutionBEList TextTokens
        {
            get
            {
                return this.TextTokensField;
            }
            set
            {
                this.TextTokensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public AltinnWebServices.WS.Prefill.ReceiverEndPointBEList ReceiverEndPoints
        {
            get
            {
                return this.ReceiverEndPointsField;
            }
            set
            {
                this.ReceiverEndPointsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationType", Namespace="http://schemas.altinn.no/services/Intermediary/Notification/2009/10")]
    public enum NotificationType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StandAlone = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TextTokenSubstitutionBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="TextToken")]
    public class TextTokenSubstitutionBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.TextToken>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiverEndPointBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="ReceiverEndPoint")]
    public class ReceiverEndPointBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.ReceiverEndPoint>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextToken", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    public partial class TextToken : object
    {
        
        private int TokenNumField;
        
        private string TokenValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TokenNum
        {
            get
            {
                return this.TokenNumField;
            }
            set
            {
                this.TokenNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenValue
        {
            get
            {
                return this.TokenValueField;
            }
            set
            {
                this.TokenValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiverEndPoint", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    public partial class ReceiverEndPoint : object
    {
        
        private System.Nullable<AltinnWebServices.WS.Prefill.TransportType> TransportTypeField;
        
        private string ReceiverAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<AltinnWebServices.WS.Prefill.TransportType> TransportType
        {
            get
            {
                return this.TransportTypeField;
            }
            set
            {
                this.TransportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ReceiverAddress
        {
            get
            {
                return this.ReceiverAddressField;
            }
            set
            {
                this.ReceiverAddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportType", Namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10")]
    public enum TransportType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMSPreferred = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailPreferred = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptExternal", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public partial class ReceiptExternal : object
    {
        
        private System.DateTime LastChangedField;
        
        private int ParentReceiptIdField;
        
        private string ReceiptHistoryField;
        
        private int ReceiptIdField;
        
        private AltinnWebServices.WS.Prefill.ReceiptStatusEnum ReceiptStatusCodeField;
        
        private string ReceiptTextField;
        
        private AltinnWebServices.WS.Prefill.ReceiptTypeEnum ReceiptTypeNameField;
        
        private AltinnWebServices.WS.Prefill.ReferenceList ReferencesField;
        
        private AltinnWebServices.WS.Prefill.ReceiptExternalList SubReceiptsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged
        {
            get
            {
                return this.LastChangedField;
            }
            set
            {
                this.LastChangedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReceiptId
        {
            get
            {
                return this.ParentReceiptIdField;
            }
            set
            {
                this.ParentReceiptIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptHistory
        {
            get
            {
                return this.ReceiptHistoryField;
            }
            set
            {
                this.ReceiptHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId
        {
            get
            {
                return this.ReceiptIdField;
            }
            set
            {
                this.ReceiptIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.ReceiptStatusEnum ReceiptStatusCode
        {
            get
            {
                return this.ReceiptStatusCodeField;
            }
            set
            {
                this.ReceiptStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptText
        {
            get
            {
                return this.ReceiptTextField;
            }
            set
            {
                this.ReceiptTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.ReceiptTypeEnum ReceiptTypeName
        {
            get
            {
                return this.ReceiptTypeNameField;
            }
            set
            {
                this.ReceiptTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.ReferenceList References
        {
            get
            {
                return this.ReferencesField;
            }
            set
            {
                this.ReferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.ReceiptExternalList SubReceipts
        {
            get
            {
                return this.SubReceiptsField;
            }
            set
            {
                this.SubReceiptsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptStatusEnum", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public enum ReceiptStatusEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnExpectedError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptTypeEnum", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public enum ReceiptTypeEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormTask = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PINCODE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDLS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSF = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LookUp = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReferenceList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="Reference")]
    public class ReferenceList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.Reference>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiptExternalList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="ReceiptExternal")]
    public class ReceiptExternalList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.ReceiptExternal>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reference", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public partial class Reference : object
    {
        
        private AltinnWebServices.WS.Prefill.ReferenceType ReferenceTypeNameField;
        
        private string ReferenceValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.ReferenceType ReferenceTypeName
        {
            get
            {
                return this.ReferenceTypeNameField;
            }
            set
            {
                this.ReferenceTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceValue
        {
            get
            {
                return this.ReferenceValueField;
            }
            set
            {
                this.ReferenceValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceType", Namespace="http://schemas.altinn.no/services/Intermediary/Shipment/2009/10")]
    public enum ReferenceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalShipmentReference = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndUserSystemReference = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentReference = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendersReference = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkFlowReference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchReference = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutboundShipmentReference = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiversReference = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Altinn1Reference = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerPartyReference = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyReference = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchiveReference = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillFormTaskDetails", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    public partial class PrefillFormTaskDetails : object
    {
        
        private AltinnWebServices.WS.Prefill.PreFillFormTaskBEList PreFillFormTasklistField;
        
        private string SystemUserCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.Prefill.PreFillFormTaskBEList PreFillFormTasklist
        {
            get
            {
                return this.PreFillFormTasklistField;
            }
            set
            {
                this.PreFillFormTasklistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SystemUserCode
        {
            get
            {
                return this.SystemUserCodeField;
            }
            set
            {
                this.SystemUserCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PreFillFormTaskBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PrefillFormTask")]
    public class PreFillFormTaskBEList : System.Collections.Generic.List<AltinnWebServices.WS.Prefill.PrefillFormTask>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10", ConfigurationName="AltinnWebServices.WS.Prefill.IPreFillExternalBasic")]
    public interface IPreFillExternalBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.Prefill.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.TestResponse> TestAsync(AltinnWebServices.WS.Prefill.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10/IPreFillExternalBasic" +
            "/SubmitAndInstantiatePrefilledFormTaskBasic", ReplyAction="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10/IPreFillExternalBasic" +
            "/SubmitAndInstantiatePrefilledFormTaskBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.Prefill.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10/IPreFillExternalBasic" +
            "/SubmitAndInstantiatePrefilledFormTaskBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.ReceiptExternal> SubmitAndInstantiatePrefilledFormTaskBasicAsync(string systemUserName, string systemPassword, string externalBatchId, AltinnWebServices.WS.Prefill.PrefillFormTask preFillFormTask, bool doSaveFormTask, bool doinstantiateFormTask, System.Nullable<int> caseId, System.Nullable<System.DateTime> dueDate, string instantitedOnBehalfOf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10/IPreFillExternalBasic" +
            "/SubmitPrefilledFormTasksBasic", ReplyAction="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10/IPreFillExternalBasic" +
            "/SubmitPrefilledFormTasksBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.Prefill.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/PreFill/2009/10/IPreFillExternalBasic" +
            "/SubmitPrefilledFormTasksBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.ReceiptExternal> SubmitPrefilledFormTasksBasicAsync(string systemUserName, string systemPassword, string externalBatchId, AltinnWebServices.WS.Prefill.PrefillFormTaskDetails preFillFormTasksDetails);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest
    {
        
        public TestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse
    {
        
        public TestResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IPreFillExternalBasicChannel : AltinnWebServices.WS.Prefill.IPreFillExternalBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class PreFillExternalBasicClient : System.ServiceModel.ClientBase<AltinnWebServices.WS.Prefill.IPreFillExternalBasic>, AltinnWebServices.WS.Prefill.IPreFillExternalBasic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PreFillExternalBasicClient() : 
                base(PreFillExternalBasicClient.GetDefaultBinding(), PreFillExternalBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPreFillExternalBasic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreFillExternalBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(PreFillExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), PreFillExternalBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreFillExternalBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PreFillExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreFillExternalBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PreFillExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreFillExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.TestResponse> AltinnWebServices.WS.Prefill.IPreFillExternalBasic.TestAsync(AltinnWebServices.WS.Prefill.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.TestResponse> TestAsync()
        {
            AltinnWebServices.WS.Prefill.TestRequest inValue = new AltinnWebServices.WS.Prefill.TestRequest();
            return ((AltinnWebServices.WS.Prefill.IPreFillExternalBasic)(this)).TestAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.ReceiptExternal> SubmitAndInstantiatePrefilledFormTaskBasicAsync(string systemUserName, string systemPassword, string externalBatchId, AltinnWebServices.WS.Prefill.PrefillFormTask preFillFormTask, bool doSaveFormTask, bool doinstantiateFormTask, System.Nullable<int> caseId, System.Nullable<System.DateTime> dueDate, string instantitedOnBehalfOf)
        {
            return base.Channel.SubmitAndInstantiatePrefilledFormTaskBasicAsync(systemUserName, systemPassword, externalBatchId, preFillFormTask, doSaveFormTask, doinstantiateFormTask, caseId, dueDate, instantitedOnBehalfOf);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.Prefill.ReceiptExternal> SubmitPrefilledFormTasksBasicAsync(string systemUserName, string systemPassword, string externalBatchId, AltinnWebServices.WS.Prefill.PrefillFormTaskDetails preFillFormTasksDetails)
        {
            return base.Channel.SubmitPrefilledFormTasksBasicAsync(systemUserName, systemPassword, externalBatchId, preFillFormTasksDetails);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPreFillExternalBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPreFillExternalBasic))
            {
                return new System.ServiceModel.EndpointAddress("https://tt02.altinn.no/ServiceEngineExternal/PreFillBasic.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PreFillExternalBasicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPreFillExternalBasic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PreFillExternalBasicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPreFillExternalBasic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPreFillExternalBasic,
        }
    }
}
