//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnWebServices.WS.AltinnDownloadQueue
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    public partial class AltinnFault : object
    {
        
        private string AltinnErrorMessageField;
        
        private string AltinnExtendedErrorMessageField;
        
        private string AltinnLocalizedErrorMessageField;
        
        private string ErrorGuidField;
        
        private int ErrorIDField;
        
        private string UserGuidField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage
        {
            get
            {
                return this.AltinnErrorMessageField;
            }
            set
            {
                this.AltinnErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage
        {
            get
            {
                return this.AltinnExtendedErrorMessageField;
            }
            set
            {
                this.AltinnExtendedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage
        {
            get
            {
                return this.AltinnLocalizedErrorMessageField;
            }
            set
            {
                this.AltinnLocalizedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid
        {
            get
            {
                return this.ErrorGuidField;
            }
            set
            {
                this.ErrorGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedFormTaskDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08")]
    public partial class ArchivedFormTaskDQBE : object
    {
        
        private AltinnWebServices.WS.AltinnDownloadQueue.ApproverListDQBE ApproversField;
        
        private string ArchiveReferenceField;
        
        private System.DateTime ArchiveTimeStampField;
        
        private AltinnWebServices.WS.AltinnDownloadQueue.ArchivedAttachmentExternalListDQBE AttachmentsField;
        
        private int AttachmentsInResponseField;
        
        private int CaseIDField;
        
        private long CorrelationReferenceField;
        
        private AltinnWebServices.WS.AltinnDownloadQueue.ArchivedFormListDQBE FormsField;
        
        private int FormsInResponseField;
        
        private string ReporteeField;
        
        private AltinnWebServices.WS.AltinnDownloadQueue.SOEncryptedSymmetricKeyExternalDQBE SOEncryptedSymmetricKeyField;
        
        private string ServiceCodeField;
        
        private string ServiceEditionCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.ApproverListDQBE Approvers
        {
            get
            {
                return this.ApproversField;
            }
            set
            {
                this.ApproversField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveReference
        {
            get
            {
                return this.ArchiveReferenceField;
            }
            set
            {
                this.ArchiveReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArchiveTimeStamp
        {
            get
            {
                return this.ArchiveTimeStampField;
            }
            set
            {
                this.ArchiveTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.ArchivedAttachmentExternalListDQBE Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachmentsInResponse
        {
            get
            {
                return this.AttachmentsInResponseField;
            }
            set
            {
                this.AttachmentsInResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseID
        {
            get
            {
                return this.CaseIDField;
            }
            set
            {
                this.CaseIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CorrelationReference
        {
            get
            {
                return this.CorrelationReferenceField;
            }
            set
            {
                this.CorrelationReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.ArchivedFormListDQBE Forms
        {
            get
            {
                return this.FormsField;
            }
            set
            {
                this.FormsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormsInResponse
        {
            get
            {
                return this.FormsInResponseField;
            }
            set
            {
                this.FormsInResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reportee
        {
            get
            {
                return this.ReporteeField;
            }
            set
            {
                this.ReporteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.SOEncryptedSymmetricKeyExternalDQBE SOEncryptedSymmetricKey
        {
            get
            {
                return this.SOEncryptedSymmetricKeyField;
            }
            set
            {
                this.SOEncryptedSymmetricKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCode
        {
            get
            {
                return this.ServiceCodeField;
            }
            set
            {
                this.ServiceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceEditionCode
        {
            get
            {
                return this.ServiceEditionCodeField;
            }
            set
            {
                this.ServiceEditionCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOEncryptedSymmetricKeyExternalDQBE", Namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08")]
    public partial class SOEncryptedSymmetricKeyExternalDQBE : object
    {
        
        private string CertificateThumbprintField;
        
        private byte[] EncryptedKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateThumbprint
        {
            get
            {
                return this.CertificateThumbprintField;
            }
            set
            {
                this.CertificateThumbprintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] EncryptedKey
        {
            get
            {
                return this.EncryptedKeyField;
            }
            set
            {
                this.EncryptedKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ApproverListDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08", ItemName="ApproverDQBE")]
    public class ApproverListDQBE : System.Collections.Generic.List<AltinnWebServices.WS.AltinnDownloadQueue.ApproverDQBE>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchivedAttachmentExternalListDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08", ItemName="ArchivedAttachmentDQBE")]
    public class ArchivedAttachmentExternalListDQBE : System.Collections.Generic.List<AltinnWebServices.WS.AltinnDownloadQueue.ArchivedAttachmentDQBE>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchivedFormListDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08", ItemName="ArchivedFormDQBE")]
    public class ArchivedFormListDQBE : System.Collections.Generic.List<AltinnWebServices.WS.AltinnDownloadQueue.ArchivedFormDQBE>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApproverDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08")]
    public partial class ApproverDQBE : object
    {
        
        private System.DateTime ApprovedTimeStampField;
        
        private string ApproverIDField;
        
        private AltinnWebServices.WS.AltinnDownloadQueue.ApproverSecurityLevel SecurityLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ApprovedTimeStamp
        {
            get
            {
                return this.ApprovedTimeStampField;
            }
            set
            {
                this.ApprovedTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApproverID
        {
            get
            {
                return this.ApproverIDField;
            }
            set
            {
                this.ApproverIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.ApproverSecurityLevel SecurityLevel
        {
            get
            {
                return this.SecurityLevelField;
            }
            set
            {
                this.SecurityLevelField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApproverSecurityLevel", Namespace="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive")]
    public enum ApproverSecurityLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        selfIdentifiedUser = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        notSensitive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lessSensitive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sensitive = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        verySensitive = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedAttachmentDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08")]
    public partial class ArchivedAttachmentDQBE : object
    {
        
        private string ArchiveReferenceField;
        
        private byte[] AttachmentDataField;
        
        private string AttachmentTypeField;
        
        private string FileNameField;
        
        private bool IsEncryptedField;
        
        private int AttachmentIdField;
        
        private string AttachmentTypeNameField;
        
        private string AttachmentTypeNameLanguageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveReference
        {
            get
            {
                return this.ArchiveReferenceField;
            }
            set
            {
                this.ArchiveReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AttachmentData
        {
            get
            {
                return this.AttachmentDataField;
            }
            set
            {
                this.AttachmentDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentType
        {
            get
            {
                return this.AttachmentTypeField;
            }
            set
            {
                this.AttachmentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEncrypted
        {
            get
            {
                return this.IsEncryptedField;
            }
            set
            {
                this.IsEncryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int AttachmentId
        {
            get
            {
                return this.AttachmentIdField;
            }
            set
            {
                this.AttachmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string AttachmentTypeName
        {
            get
            {
                return this.AttachmentTypeNameField;
            }
            set
            {
                this.AttachmentTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string AttachmentTypeNameLanguage
        {
            get
            {
                return this.AttachmentTypeNameLanguageField;
            }
            set
            {
                this.AttachmentTypeNameLanguageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedFormDQBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2012/08")]
    public partial class ArchivedFormDQBE : object
    {
        
        private string DataFormatIDField;
        
        private int DataFormatVersionIDField;
        
        private string FormDataField;
        
        private string ParentReferenceField;
        
        private string ReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFormatID
        {
            get
            {
                return this.DataFormatIDField;
            }
            set
            {
                this.DataFormatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFormatVersionID
        {
            get
            {
                return this.DataFormatVersionIDField;
            }
            set
            {
                this.DataFormatVersionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormData
        {
            get
            {
                return this.FormDataField;
            }
            set
            {
                this.FormDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentReference
        {
            get
            {
                return this.ParentReferenceField;
            }
            set
            {
                this.ParentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DownloadQueueItemBEList", Namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08", ItemName="DownloadQueueItemBE")]
    public class DownloadQueueItemBEList : System.Collections.Generic.List<AltinnWebServices.WS.AltinnDownloadQueue.DownloadQueueItemBE>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadQueueItemBE", Namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2012/08")]
    public partial class DownloadQueueItemBE : object
    {
        
        private string ArchiveReferenceField;
        
        private System.DateTime ArchivedDateField;
        
        private string ReporteeIDField;
        
        private AltinnWebServices.WS.AltinnDownloadQueue.DownloadQueueReporteeType ReporteeTypeField;
        
        private string ServiceCodeField;
        
        private int ServiceEditionCodeField;
        
        private AltinnWebServices.WS.AltinnDownloadQueue.ArchivedShipmentMetadataList ShipmentMetadataListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveReference
        {
            get
            {
                return this.ArchiveReferenceField;
            }
            set
            {
                this.ArchiveReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArchivedDate
        {
            get
            {
                return this.ArchivedDateField;
            }
            set
            {
                this.ArchivedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReporteeID
        {
            get
            {
                return this.ReporteeIDField;
            }
            set
            {
                this.ReporteeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.DownloadQueueReporteeType ReporteeType
        {
            get
            {
                return this.ReporteeTypeField;
            }
            set
            {
                this.ReporteeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCode
        {
            get
            {
                return this.ServiceCodeField;
            }
            set
            {
                this.ServiceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceEditionCode
        {
            get
            {
                return this.ServiceEditionCodeField;
            }
            set
            {
                this.ServiceEditionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AltinnWebServices.WS.AltinnDownloadQueue.ArchivedShipmentMetadataList ShipmentMetadataList
        {
            get
            {
                return this.ShipmentMetadataListField;
            }
            set
            {
                this.ShipmentMetadataListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadQueueReporteeType", Namespace="http://schemas.datacontract.org/2004/07/Altinn.Common.SBL.Enums.Archive")]
    public enum DownloadQueueReporteeType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organisation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Person = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Selfregistereduser = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchivedShipmentMetadataList", Namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2019/01", ItemName="ArchivedShipmentMetadata")]
    public class ArchivedShipmentMetadataList : System.Collections.Generic.List<AltinnWebServices.WS.AltinnDownloadQueue.ArchivedShipmentMetadata>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedShipmentMetadata", Namespace="http://schemas.altinn.no/services/Archive/DownloadQueue/2019/01")]
    public partial class ArchivedShipmentMetadata : object
    {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08", ConfigurationName="AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic")]
    public interface IDownloadQueueExternalBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.AltinnDownloadQueue.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.TestResponse> TestAsync(AltinnWebServices.WS.AltinnDownloadQueue.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetArchivedFormTaskBasicDQ", ReplyAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetArchivedFormTaskBasicDQResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.AltinnDownloadQueue.AltinnFault), Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetArchivedFormTaskBasicDQAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.ArchivedFormTaskDQBE> GetArchivedFormTaskBasicDQAsync(string systemUserName, string systemPassword, string archiveReference, System.Nullable<int> languageID, bool includeXmlNamespace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetDownloadQueueItems", ReplyAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetDownloadQueueItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.AltinnDownloadQueue.AltinnFault), Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetDownloadQueueItemsAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.DownloadQueueItemBEList> GetDownloadQueueItemsAsync(string systemUserName, string systemPassword, string serviceCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/PurgeItem", ReplyAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/PurgeItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.AltinnDownloadQueue.AltinnFault), Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/PurgeItemAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<string> PurgeItemAsync(string systemUserName, string systemPassword, string archiveReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetFormSetPdfBasic", ReplyAction="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetFormSetPdfBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.AltinnDownloadQueue.AltinnFault), Action="http://www.altinn.no/services/Archive/DownloadQueue/2012/08/IDownloadQueueExterna" +
            "lBasic/GetFormSetPdfBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicResponse> GetFormSetPdfBasicAsync(AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest
    {
        
        public TestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse
    {
        
        public TestResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormSetPdfBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormSetPdfBasic", Namespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08", Order=0)]
        public AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequestBody Body;
        
        public GetFormSetPdfBasicRequest()
        {
        }
        
        public GetFormSetPdfBasicRequest(AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08")]
    public partial class GetFormSetPdfBasicRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string archiveReference;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int languageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string dataFormatId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> dataFormatVersion;
        
        public GetFormSetPdfBasicRequestBody()
        {
        }
        
        public GetFormSetPdfBasicRequestBody(string systemName, string systemPassword, string archiveReference, int languageId, string dataFormatId, System.Nullable<int> dataFormatVersion)
        {
            this.systemName = systemName;
            this.systemPassword = systemPassword;
            this.archiveReference = archiveReference;
            this.languageId = languageId;
            this.dataFormatId = dataFormatId;
            this.dataFormatVersion = dataFormatVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormSetPdfBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormSetPdfBasicResponse", Namespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08", Order=0)]
        public AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicResponseBody Body;
        
        public GetFormSetPdfBasicResponse()
        {
        }
        
        public GetFormSetPdfBasicResponse(AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/DownloadQueue/2012/08")]
    public partial class GetFormSetPdfBasicResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] GetFormSetPdfBasicResult;
        
        public GetFormSetPdfBasicResponseBody()
        {
        }
        
        public GetFormSetPdfBasicResponseBody(byte[] GetFormSetPdfBasicResult)
        {
            this.GetFormSetPdfBasicResult = GetFormSetPdfBasicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IDownloadQueueExternalBasicChannel : AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class DownloadQueueExternalBasicClient : System.ServiceModel.ClientBase<AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic>, AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DownloadQueueExternalBasicClient() : 
                base(DownloadQueueExternalBasicClient.GetDefaultBinding(), DownloadQueueExternalBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDownloadQueueExternalBasic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadQueueExternalBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(DownloadQueueExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), DownloadQueueExternalBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadQueueExternalBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DownloadQueueExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadQueueExternalBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DownloadQueueExternalBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadQueueExternalBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.TestResponse> AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic.TestAsync(AltinnWebServices.WS.AltinnDownloadQueue.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.TestResponse> TestAsync()
        {
            AltinnWebServices.WS.AltinnDownloadQueue.TestRequest inValue = new AltinnWebServices.WS.AltinnDownloadQueue.TestRequest();
            return ((AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic)(this)).TestAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.ArchivedFormTaskDQBE> GetArchivedFormTaskBasicDQAsync(string systemUserName, string systemPassword, string archiveReference, System.Nullable<int> languageID, bool includeXmlNamespace)
        {
            return base.Channel.GetArchivedFormTaskBasicDQAsync(systemUserName, systemPassword, archiveReference, languageID, includeXmlNamespace);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.DownloadQueueItemBEList> GetDownloadQueueItemsAsync(string systemUserName, string systemPassword, string serviceCode)
        {
            return base.Channel.GetDownloadQueueItemsAsync(systemUserName, systemPassword, serviceCode);
        }
        
        public System.Threading.Tasks.Task<string> PurgeItemAsync(string systemUserName, string systemPassword, string archiveReference)
        {
            return base.Channel.PurgeItemAsync(systemUserName, systemPassword, archiveReference);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicResponse> AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic.GetFormSetPdfBasicAsync(AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequest request)
        {
            return base.Channel.GetFormSetPdfBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicResponse> GetFormSetPdfBasicAsync(string systemName, string systemPassword, string archiveReference, int languageId, string dataFormatId, System.Nullable<int> dataFormatVersion)
        {
            AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequest inValue = new AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequest();
            inValue.Body = new AltinnWebServices.WS.AltinnDownloadQueue.GetFormSetPdfBasicRequestBody();
            inValue.Body.systemName = systemName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.archiveReference = archiveReference;
            inValue.Body.languageId = languageId;
            inValue.Body.dataFormatId = dataFormatId;
            inValue.Body.dataFormatVersion = dataFormatVersion;
            return ((AltinnWebServices.WS.AltinnDownloadQueue.IDownloadQueueExternalBasic)(this)).GetFormSetPdfBasicAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDownloadQueueExternalBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDownloadQueueExternalBasic))
            {
                return new System.ServiceModel.EndpointAddress("https://tt02.altinn.no/ArchiveExternal/DownloadQueueExternalBasic.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DownloadQueueExternalBasicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDownloadQueueExternalBasic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DownloadQueueExternalBasicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDownloadQueueExternalBasic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDownloadQueueExternalBasic,
        }
    }
}
