//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace no.kxml.skjema.dibk.arbeidstilsynetsSamtykke {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Kode", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class KodeType {
        
        private string kodeverdiField;
        
        private string kodebeskrivelseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kodeverdi {
            get {
                return this.kodeverdiField;
            }
            set {
                this.kodeverdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kodebeskrivelse {
            get {
                return this.kodebeskrivelseField;
            }
            set {
                this.kodebeskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Arbeidsplasser", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class ArbeidsplasserType {
        
        private System.Nullable<bool> framtidigeField;
        
        private bool framtidigeFieldSpecified;
        
        private System.Nullable<bool> fasteField;
        
        private bool fasteFieldSpecified;
        
        private System.Nullable<bool> midlertidigeField;
        
        private bool midlertidigeFieldSpecified;
        
        private string antallAnsatteField;
        
        private System.Nullable<bool> eksisterendeField;
        
        private bool eksisterendeFieldSpecified;
        
        private System.Nullable<bool> utleieByggField;
        
        private bool utleieByggFieldSpecified;
        
        private string antallVirksomheterField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> framtidige {
            get {
                return this.framtidigeField;
            }
            set {
                this.framtidigeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool framtidigeSpecified {
            get {
                return this.framtidigeFieldSpecified;
            }
            set {
                this.framtidigeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> faste {
            get {
                return this.fasteField;
            }
            set {
                this.fasteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fasteSpecified {
            get {
                return this.fasteFieldSpecified;
            }
            set {
                this.fasteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> midlertidige {
            get {
                return this.midlertidigeField;
            }
            set {
                this.midlertidigeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool midlertidigeSpecified {
            get {
                return this.midlertidigeFieldSpecified;
            }
            set {
                this.midlertidigeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string antallAnsatte {
            get {
                return this.antallAnsatteField;
            }
            set {
                this.antallAnsatteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> eksisterende {
            get {
                return this.eksisterendeField;
            }
            set {
                this.eksisterendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eksisterendeSpecified {
            get {
                return this.eksisterendeFieldSpecified;
            }
            set {
                this.eksisterendeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> utleieBygg {
            get {
                return this.utleieByggField;
            }
            set {
                this.utleieByggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utleieByggSpecified {
            get {
                return this.utleieByggFieldSpecified;
            }
            set {
                this.utleieByggFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string antallVirksomheter {
            get {
                return this.antallVirksomheterField;
            }
            set {
                this.antallVirksomheterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjon", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class DispensasjonType {
        
        private KodeType dispensasjonstypeField;
        
        private string begrunnelseField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType dispensasjonstype {
            get {
                return this.dispensasjonstypeField;
            }
            set {
                this.dispensasjonstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string begrunnelse {
            get {
                return this.begrunnelseField;
            }
            set {
                this.begrunnelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("EiendommensAdresse", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class EiendommensAdresseType {
        
        private string adresselinje1Field;
        
        private string adresselinje2Field;
        
        private string adresselinje3Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landkodeField;
        
        private string gatenavnField;
        
        private string husnrField;
        
        private string bokstavField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje1 {
            get {
                return this.adresselinje1Field;
            }
            set {
                this.adresselinje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje2 {
            get {
                return this.adresselinje2Field;
            }
            set {
                this.adresselinje2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje3 {
            get {
                return this.adresselinje3Field;
            }
            set {
                this.adresselinje3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string landkode {
            get {
                return this.landkodeField;
            }
            set {
                this.landkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gatenavn {
            get {
                return this.gatenavnField;
            }
            set {
                this.gatenavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string husnr {
            get {
                return this.husnrField;
            }
            set {
                this.husnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bokstav {
            get {
                return this.bokstavField;
            }
            set {
                this.bokstavField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Fakturamottaker", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class FakturamottakerType {
        
        private string organisasjonsnummerField;
        
        private string bestillerReferanseField;
        
        private string fakturareferanserField;
        
        private string navnField;
        
        private string prosjektnummerField;
        
        private System.Nullable<bool> ehfFakturaField;
        
        private bool ehfFakturaFieldSpecified;
        
        private System.Nullable<bool> fakturaPapirField;
        
        private bool fakturaPapirFieldSpecified;
        
        private EnkelAdresseType adresseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organisasjonsnummer {
            get {
                return this.organisasjonsnummerField;
            }
            set {
                this.organisasjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bestillerReferanse {
            get {
                return this.bestillerReferanseField;
            }
            set {
                this.bestillerReferanseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fakturareferanser {
            get {
                return this.fakturareferanserField;
            }
            set {
                this.fakturareferanserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosjektnummer {
            get {
                return this.prosjektnummerField;
            }
            set {
                this.prosjektnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ehfFaktura {
            get {
                return this.ehfFakturaField;
            }
            set {
                this.ehfFakturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ehfFakturaSpecified {
            get {
                return this.ehfFakturaFieldSpecified;
            }
            set {
                this.ehfFakturaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> fakturaPapir {
            get {
                return this.fakturaPapirField;
            }
            set {
                this.fakturaPapirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fakturaPapirSpecified {
            get {
                return this.fakturaPapirFieldSpecified;
            }
            set {
                this.fakturaPapirFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnkelAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("EnkelAdresse", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class EnkelAdresseType {
        
        private string adresselinje1Field;
        
        private string adresselinje2Field;
        
        private string adresselinje3Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landkodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje1 {
            get {
                return this.adresselinje1Field;
            }
            set {
                this.adresselinje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje2 {
            get {
                return this.adresselinje2Field;
            }
            set {
                this.adresselinje2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje3 {
            get {
                return this.adresselinje3Field;
            }
            set {
                this.adresselinje3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string landkode {
            get {
                return this.landkodeField;
            }
            set {
                this.landkodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Formaal", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class FormaalType {
        
        private KodeType anleggstypeField;
        
        private KodeType naeringsgruppeField;
        
        private KodeType bygningstypeField;
        
        private KodeType[] tiltaksformaalField;
        
        private string beskrivPlanlagtFormaalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType anleggstype {
            get {
                return this.anleggstypeField;
            }
            set {
                this.anleggstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType naeringsgruppe {
            get {
                return this.naeringsgruppeField;
            }
            set {
                this.naeringsgruppeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType bygningstype {
            get {
                return this.bygningstypeField;
            }
            set {
                this.bygningstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tiltaksformaal", IsNullable=true)]
        public KodeType[] tiltaksformaal {
            get {
                return this.tiltaksformaalField;
            }
            set {
                this.tiltaksformaalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivPlanlagtFormaal {
            get {
                return this.beskrivPlanlagtFormaalField;
            }
            set {
                this.beskrivPlanlagtFormaalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Kontaktperson", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class KontaktpersonType {
        
        private string navnField;
        
        private string telefonnummerField;
        
        private string mobilnummerField;
        
        private string epostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilnummer {
            get {
                return this.mobilnummerField;
            }
            set {
                this.mobilnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Saksnummer", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class SaksnummerType {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Tiltak", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class TiltakType {
        
        private FormaalType brukField;
        
        private KodeType[] typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FormaalType bruk {
            get {
                return this.brukField;
            }
            set {
                this.brukField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public KodeType[] type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("ArbeidstilsynetsSamtykke", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class ArbeidstilsynetsSamtykkeType {
        
        private EiendomType eiendomByggestedField;
        
        private PartType tiltakshaverField;
        
        private ArbeidsplasserType arbeidsplasserField;
        
        private FakturamottakerType fakturamottakerField;
        
        private string hovedinnsendingsnummerField;
        
        private SignaturType signaturField;
        
        private string sluttbrukersystemUrlField;
        
        private string fraSluttbrukersystemField;
        
        private PartType ansvarligSoekerField;
        
        private string prosjektnavnField;
        
        private DispensasjonType[] dispensasjonField;
        
        private TiltakType[] beskrivelseAvTiltakField;
        
        private SaksnummerType kommunensSaksnummerField;
        
        private SaksnummerType arbeidstilsynetsSaksnummerField;
        
        private string dataFormatProviderField;
        
        private string dataFormatIdField;
        
        private string dataFormatVersionField;
        
        public ArbeidstilsynetsSamtykkeType() {
            this.dataFormatProviderField = "SERES";
            this.dataFormatIdField = "5547";
            this.dataFormatVersionField = "41999";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EiendomType eiendomByggested {
            get {
                return this.eiendomByggestedField;
            }
            set {
                this.eiendomByggestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PartType tiltakshaver {
            get {
                return this.tiltakshaverField;
            }
            set {
                this.tiltakshaverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArbeidsplasserType arbeidsplasser {
            get {
                return this.arbeidsplasserField;
            }
            set {
                this.arbeidsplasserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FakturamottakerType fakturamottaker {
            get {
                return this.fakturamottakerField;
            }
            set {
                this.fakturamottakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hovedinnsendingsnummer {
            get {
                return this.hovedinnsendingsnummerField;
            }
            set {
                this.hovedinnsendingsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SignaturType signatur {
            get {
                return this.signaturField;
            }
            set {
                this.signaturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sluttbrukersystemUrl {
            get {
                return this.sluttbrukersystemUrlField;
            }
            set {
                this.sluttbrukersystemUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fraSluttbrukersystem {
            get {
                return this.fraSluttbrukersystemField;
            }
            set {
                this.fraSluttbrukersystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PartType ansvarligSoeker {
            get {
                return this.ansvarligSoekerField;
            }
            set {
                this.ansvarligSoekerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosjektnavn {
            get {
                return this.prosjektnavnField;
            }
            set {
                this.prosjektnavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dispensasjon", IsNullable=false)]
        public DispensasjonType[] dispensasjon {
            get {
                return this.dispensasjonField;
            }
            set {
                this.dispensasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tiltak", IsNullable=false)]
        public TiltakType[] beskrivelseAvTiltak {
            get {
                return this.beskrivelseAvTiltakField;
            }
            set {
                this.beskrivelseAvTiltakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SaksnummerType kommunensSaksnummer {
            get {
                return this.kommunensSaksnummerField;
            }
            set {
                this.kommunensSaksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SaksnummerType arbeidstilsynetsSaksnummer {
            get {
                return this.arbeidstilsynetsSaksnummerField;
            }
            set {
                this.arbeidstilsynetsSaksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatProvider {
            get {
                return this.dataFormatProviderField;
            }
            set {
                this.dataFormatProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatId {
            get {
                return this.dataFormatIdField;
            }
            set {
                this.dataFormatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatVersion {
            get {
                return this.dataFormatVersionField;
            }
            set {
                this.dataFormatVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Eiendom", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class EiendomType {
        
        private EiendommensAdresseType adresseField;
        
        private MatrikkelnummerType eiendomsidentifikasjonField;
        
        private string bygningsnummerField;
        
        private string bolignummerField;
        
        private string kommunenavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EiendommensAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelnummerType eiendomsidentifikasjon {
            get {
                return this.eiendomsidentifikasjonField;
            }
            set {
                this.eiendomsidentifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bygningsnummer {
            get {
                return this.bygningsnummerField;
            }
            set {
                this.bygningsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bolignummer {
            get {
                return this.bolignummerField;
            }
            set {
                this.bolignummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommunenavn {
            get {
                return this.kommunenavnField;
            }
            set {
                this.kommunenavnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelnummer", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class MatrikkelnummerType {
        
        private string kommunenummerField;
        
        private string gaardsnummerField;
        
        private string bruksnummerField;
        
        private string festenummerField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommunenummer {
            get {
                return this.kommunenummerField;
            }
            set {
                this.kommunenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string gaardsnummer {
            get {
                return this.gaardsnummerField;
            }
            set {
                this.gaardsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string bruksnummer {
            get {
                return this.bruksnummerField;
            }
            set {
                this.bruksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string festenummer {
            get {
                return this.festenummerField;
            }
            set {
                this.festenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Part", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class PartType {
        
        private KodeType partstypeField;
        
        private string foedselsnummerField;
        
        private string organisasjonsnummerField;
        
        private string navnField;
        
        private EnkelAdresseType adresseField;
        
        private string telefonnummerField;
        
        private string mobilnummerField;
        
        private string epostField;
        
        private KontaktpersonType kontaktpersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType partstype {
            get {
                return this.partstypeField;
            }
            set {
                this.partstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string foedselsnummer {
            get {
                return this.foedselsnummerField;
            }
            set {
                this.foedselsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organisasjonsnummer {
            get {
                return this.organisasjonsnummerField;
            }
            set {
                this.organisasjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnkelAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilnummer {
            get {
                return this.mobilnummerField;
            }
            set {
                this.mobilnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KontaktpersonType kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke")]
    [System.Xml.Serialization.XmlRootAttribute("Signatur", Namespace="http://skjema.kxml.no/dibk/arbeidstilsynetsSamtykke", IsNullable=false)]
    public partial class SignaturType {
        
        private System.Nullable<System.DateTime> signaturdatoField;
        
        private bool signaturdatoFieldSpecified;
        
        private string signertAvField;
        
        private string signertPaaVegneAvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> signaturdato {
            get {
                return this.signaturdatoField;
            }
            set {
                this.signaturdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signaturdatoSpecified {
            get {
                return this.signaturdatoFieldSpecified;
            }
            set {
                this.signaturdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signertAv {
            get {
                return this.signertAvField;
            }
            set {
                this.signertAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signertPaaVegneAv {
            get {
                return this.signertPaaVegneAvField;
            }
            set {
                this.signertPaaVegneAvField = value;
            }
        }
    }
}
