//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    public partial class AltinnFault : object
    {
        
        private string AltinnErrorMessageField;
        
        private string AltinnExtendedErrorMessageField;
        
        private string AltinnLocalizedErrorMessageField;
        
        private string ErrorGuidField;
        
        private int ErrorIDField;
        
        private string UserGuidField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage
        {
            get
            {
                return this.AltinnErrorMessageField;
            }
            set
            {
                this.AltinnErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage
        {
            get
            {
                return this.AltinnExtendedErrorMessageField;
            }
            set
            {
                this.AltinnExtendedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage
        {
            get
            {
                return this.AltinnLocalizedErrorMessageField;
            }
            set
            {
                this.AltinnLocalizedErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid
        {
            get
            {
                return this.ErrorGuidField;
            }
            set
            {
                this.ErrorGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06", ConfigurationName="AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExte" +
        "rnalStreamedBasic")]
    public interface IServiceOwnerArchiveExternalStreamedBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestResponse> TestAsync(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasic", ReplyAction="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.AltinnFault), Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        System.Threading.Tasks.Task<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse> GetAttachmentDataStreamedBasicAsync(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest
    {
        
        public TestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse
    {
        
        public TestResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentDataStreamedBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentDataStreamedBasic", Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06", Order=0)]
        public AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody Body;
        
        public GetAttachmentDataStreamedBasicRequest()
        {
        }
        
        public GetAttachmentDataStreamedBasicRequest(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06")]
    public partial class GetAttachmentDataStreamedBasicRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int attachmentId;
        
        public GetAttachmentDataStreamedBasicRequestBody()
        {
        }
        
        public GetAttachmentDataStreamedBasicRequestBody(string systemUserName, string systemPassword, int attachmentId)
        {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.attachmentId = attachmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentDataStreamedBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentDataStreamedBasicResponse", Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06", Order=0)]
        public AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponseBody Body;
        
        public GetAttachmentDataStreamedBasicResponse()
        {
        }
        
        public GetAttachmentDataStreamedBasicResponse(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06")]
    public partial class GetAttachmentDataStreamedBasicResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] GetAttachmentDataStreamedBasicResult;
        
        public GetAttachmentDataStreamedBasicResponseBody()
        {
        }
        
        public GetAttachmentDataStreamedBasicResponseBody(byte[] GetAttachmentDataStreamedBasicResult)
        {
            this.GetAttachmentDataStreamedBasicResult = GetAttachmentDataStreamedBasicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IServiceOwnerArchiveExternalStreamedBasicChannel : AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ServiceOwnerArchiveExternalStreamedBasicClient : System.ServiceModel.ClientBase<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic>, AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceOwnerArchiveExternalStreamedBasicClient() : 
                base(ServiceOwnerArchiveExternalStreamedBasicClient.GetDefaultBinding(), ServiceOwnerArchiveExternalStreamedBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceOwnerArchiveExternalStreamedBasic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceOwnerArchiveExternalStreamedBasicClient.GetBindingForEndpoint(endpointConfiguration), ServiceOwnerArchiveExternalStreamedBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceOwnerArchiveExternalStreamedBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceOwnerArchiveExternalStreamedBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestResponse> AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic.TestAsync(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestResponse> TestAsync()
        {
            AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestRequest inValue = new AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.TestRequest();
            return ((AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse> AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic.GetAttachmentDataStreamedBasicAsync(AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest request)
        {
            return base.Channel.GetAttachmentDataStreamedBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse> GetAttachmentDataStreamedBasicAsync(string systemUserName, string systemPassword, int attachmentId)
        {
            AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest inValue = new AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest();
            inValue.Body = new AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.attachmentId = attachmentId;
            return ((AltinnWebServices.WS.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic)(this)).GetAttachmentDataStreamedBasicAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceOwnerArchiveExternalStreamedBasic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceOwnerArchiveExternalStreamedBasic))
            {
                return new System.ServiceModel.EndpointAddress("https://tt02.altinn.no/ArchiveExternal/ServiceOwnerArchiveExternalStreamedBasic.s" +
                        "vc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceOwnerArchiveExternalStreamedBasicClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceOwnerArchiveExternalStreamedBasic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceOwnerArchiveExternalStreamedBasicClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceOwnerArchiveExternalStreamedBasic);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceOwnerArchiveExternalStreamedBasic,
        }
    }
}
